cyberLP/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from jet.dashboard.dashboard_modules import google_analytics_views
from order import views as order
from order.api import views as api
from page_editor.sites import site as page_site

router = routers.DefaultRouter()
router.register(r'statusboard', api.StatusViewSet)
router.register(r'status', api.StatusNameViewSet)
router.register(r'comment', api.CommentViewSet)
router.register(r'commentfiles', api.CommentFilesViewSet)
router.register(r'orders', api.OrderViewSet)
router.register(r'task', api.TaskViewSet)
router.register(r'todo', api.TodoViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/order_pages/', order.orders),
    url(r'^admin/page_editor/', include(page_site.urls)),
    url(r'^', include('page_editor.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

page_editor/urls.py
from django.conf.urls import url
from page_editor import views

urlpatterns = [
    url(r'^js/get_snippets$', views.get_snippet, name='page_editor.snippet'),
    url(r'^(?P<url>.*)$', views.flatpage, name='page_editor.page'),

]

page_editor/models.py
from constance import config
from django.db import models
from django.urls import get_script_prefix
from django.utils.encoding import iri_to_uri
from django.utils.translation import ugettext_lazy as _
from meta.models import ModelMeta
from mptt.models import MPTTModel, TreeForeignKey
from page_editor.widgets import PRNotesField


class PageBrowser(models.Model):
    class Meta:
        managed = False
        verbose_name = ("Редактор файлов")
        verbose_name_plural = ("Редактор файлов")


class Page(MPTTModel, ModelMeta):
    url = models.CharField(_('URL'), max_length=100, db_index=True)
    title = models.CharField(_('title'), max_length=200)
    content = PRNotesField(_('content'), blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
                            verbose_name='Родительская страница', db_index=True)
    creation_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    changed_date = models.DateTimeField(auto_now=True, null=True, blank=True)
    show_in_menu = models.BooleanField(verbose_name="Показывать в меню",
                                       help_text="Показывать данную страницу в меню сайта", default=True)
    dynamic = models.BooleanField(verbose_name="Динамическая", help_text="Страница с диномическим контентом",
                                  default=False)
    static = models.BooleanField(verbose_name="Статическая", help_text="Страница с статическим контентом",
                                  default=True)
    html_render = models.TextField(verbose_name="Внутренние элементы", null=True, blank=True)
    seo_description = models.TextField(verbose_name="SEO Описание", null=True, blank=True)
    seo_keywords = models.TextField(verbose_name="SEO слова", blank=True)

    class Meta:
        verbose_name = ("Cтраница")
        ordering = ('url',)
        verbose_name_plural = ("Страницы")

    def __str__(self):
        return "%s -- %s" % (self.url, self.title)

    _metadata = {
        'title': 'get_seo_title',
        'locale': 'ru_RU',
        'use_title_tag': 'True',
        'keywords':'get_keywords',
        'description':'get_description'
    }

    def get_keywords(self):
        return self.seo_keywords.strip().split(',')

    def get_seo_title(self):
        return self.title + ' | ' + config.NAME_SITE

    def get_absolute_url(self):
        # Handle script prefix manually because we bypass reverse()
        return iri_to_uri(get_script_prefix().rstrip('/') + self.url)

    def get_description(self):
        return self.seo_description

page_editor/forms.py
# coding: utf-8

import os
import re

from django import forms
from django.utils.translation import ugettext_lazy as _

from page_editor.settings import FOLDER_REGEX
from page_editor.utils import convert_filename

ALNUM_NAME_RE = re.compile(FOLDER_REGEX, re.U)

TRANSPOSE_CHOICES = (
    ("", u"-----"),
    ("0", _(u"Flip horizontal")),
    ("1", _(u"Flip vertical")),
    ("2", _(u"Rotate 90° CW")),
    ("4", _(u"Rotate 90° CCW")),
    ("3", _(u"Rotate 180°")),
)


class CreateDirForm(forms.Form):
    """
    Form for creating a folder.
    """

    name = forms.CharField(widget=forms.TextInput(attrs=dict({'class': 'vTextField'}, max_length=50, min_length=3)),
                           label=_(u'Name'),
                           help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'),
                           required=True)

    def __init__(self, path, *args, **kwargs):
        self.path = path
        self.site = kwargs.pop("page_editor_site", None)
        super(CreateDirForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        "validate name"
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not ALNUM_NAME_RE.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # Folder must not already exist.
            if self.site.storage.isdir(os.path.join(self.path, convert_filename(self.cleaned_data['name']))):
                raise forms.ValidationError(_(u'The Folder already exists.'))
        return convert_filename(self.cleaned_data['name'])


class ChangeForm(forms.Form):
    """
    Form for renaming a file/folder.
    """

    custom_action = forms.ChoiceField(label=_(u'Actions'), required=False)
    name = forms.CharField(widget=forms.TextInput(attrs=dict({'class': 'vTextField'}, max_length=50, min_length=3)),
                           label=_(u'Name'),
                           help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'),
                           required=True)
    text = forms.CharField(widget=forms.Textarea(attrs=dict({'class': 'html-editor'}, min_length=3)), label=_(u'Text'),
                           required=True)

    def __init__(self, *args, **kwargs):
        self.path = kwargs.pop("path", None)
        self.fileobject = kwargs.pop("fileobject", None)
        self.site = kwargs.pop("filebrowser_site", None)
        super(ChangeForm, self).__init__(*args, **kwargs)

        # Initialize choices of custom action
        choices = [("", u"-----")]
        for name, action in self.site.applicable_actions(self.fileobject):
            choices.append((name, action.short_description))
        self.fields['custom_action'].choices = choices

    def clean_name(self):
        "validate name"
        if self.cleaned_data['name']:
            # only letters, numbers, underscores, spaces and hyphens are allowed.
            if not ALNUM_NAME_RE.search(self.cleaned_data['name']):
                raise forms.ValidationError(_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'))
            # folder/file must not already exist.
            if self.site.storage.isdir(
                    os.path.join(self.path, convert_filename(self.cleaned_data['name']))) and os.path.join(self.path,
                                                                                                           convert_filename(
                                                                                                               self.cleaned_data[
                                                                                                                   'name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The Folder already exists.'))
            elif self.site.storage.isfile(
                    os.path.join(self.path, convert_filename(self.cleaned_data['name']))) and os.path.join(self.path,
                                                                                                           convert_filename(
                                                                                                               self.cleaned_data[
                                                                                                                   'name'])) != self.fileobject.path:
                raise forms.ValidationError(_(u'The File already exists.'))
        return convert_filename(self.cleaned_data['name'])


class FileForm(forms.Form):
    """
    Form for renaming a file/folder.
    """
    name = forms.CharField(widget=forms.TextInput(attrs=dict({'class': 'vTextField'}, max_length=50, min_length=3)),
                           label=_(u'Name'),
                           help_text=_(u'Only letters, numbers, underscores, spaces and hyphens are allowed.'),
                           required=True)
    text = forms.CharField(widget=forms.Textarea(attrs=dict({'class': 'html-editor'}, min_length=3)), label=_(u'Text'),
                           required=True)

    def __init__(self, *args, **kwargs):
        self.path = kwargs.pop("path", None)
        self.site = kwargs.pop("filebrowser_site", None)
        super(FileForm, self).__init__(*args, **kwargs)

    def clean_name(self):
        """validate name"""
        return convert_filename(self.cleaned_data['name'])

page_editor/views.py
from django.conf import settings
from django.http import Http404, HttpResponse, HttpResponsePermanentRedirect
from django.shortcuts import get_object_or_404
from django.template import Context, Template
from django.template import loader
from django.utils.safestring import mark_safe
from django.views.decorators.csrf import csrf_protect

from page_editor.models import *

DEFAULT_TEMPLATE = settings.DEFAULT_TEMPLATE

from constance import config


def flatpage(request, url, slug=''):
    print(slug)
    if not url.startswith('/'):
        url = '/' + url
    try:
        f = get_object_or_404(Page, url=url)
    except Http404:
        if not url.endswith('/') and settings.APPEND_SLASH:
            url += '/'
            f = get_object_or_404(Page, url=url)
            return HttpResponsePermanentRedirect('%s/' % request.path)
        else:
            raise
    return render_flatpage(request, f)


@csrf_protect
def render_flatpage(request, f):
    template = loader.get_template(DEFAULT_TEMPLATE)
    if f.dynamic and not f.static:
        tem = Template(f.html_render)
        con = Context({'pages': Page.objects.all(),
                       })
        menu_html = tem.render(con)
        f.content = menu_html
    if f.dynamic and f.static:
        tem = Template(f.html_render)
        con = Context({'pages': Page.objects.all(),
                       })
        menu_html = tem.render(con)
        f.content += menu_html
    # You can print html content using "html" method of HtmlNodeList object
    f.title = mark_safe(f.title)
    f.content = mark_safe(f.content)
    response = HttpResponse(template.render(
        {
            'meta': f.as_meta(request),
            'flatpage': f,
            'NAME_SITE': config.NAME_SITE,
            'PHONE': config.PHONE,
            'PHONE_ADDITION': config.PHONE_ADDITION,
            'EMAIL': config.EMAIL,
            'COMPANY_NAME': config.COMPANY_NAME,
            'pages': Page.objects.all(),
        }, request))
    return response


def get_snippet(request):
    template = loader.get_template(settings.SNIPPET_TEMPLATE)
    response = HttpResponse(template.render(
        {'NAME_SITE': config.NAME_SITE,
         'PHONE': config.PHONE,
         'PHONE_ADDITION': config.PHONE_ADDITION,
         'EMAIL': config.EMAIL,
         'COMPANY_NAME': config.COMPANY_NAME,
         'pages': Page.objects.all(),
         }, request))
    return response

page_editor/templates/page_editor/create_file.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load admin_static i18n fb_tags fb_versions fb_compat %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
    <style>
    .html-editor{
        width: 100%;
        height: 350px;
        margin-top: 30px;
    }
    </style>
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static_jquery %}"></script>
    <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
    <script type="text/javascript">
    (function($) {
        $(document).ready(function() {
            // remove edit module if no actions are given
            if ($("select#id_custom_action").find("option").length <= 1) {
                $("fieldset#fieldset_edit").hide();
            }
        });
    })(django.jQuery);
    </script>
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}
{% block coltype %}colM{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "page_editor/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <!-- POP-UP BREADCRUMBS -->
    {% if query.pop %}
        {% include "page_editor/include/breadcrumbs.html" %}
    {% endif %}
    <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post">{% csrf_token %}
        <div>
            {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
            <fieldset class="module aligned">
                <div class="form-row field-{{ form.name.name }}{% if form.name.errors %} errors{% endif %}">
                    {% if form.name.errors %}{{ form.name.errors }}{% endif %}
                    <div>
                        <label class="required" for="id_name">{{ form.name.label }}</label>
                        {{ form.name }}
                        {% if form.name.help_text %}<p class="help">{{ form.name.help_text|safe }}</p>{% endif %}
                    </div>
                <div>

                         {{ form.text }}

                </div>


                </div>
            </fieldset>
            <div class="submit-row">
                <p class="deletelink-box">
                    <a href="{% url 'page_editor:fb_delete_confirm' %}{% query_string %}" class="deletelink">{% trans "Delete" %}</a>
                </p>
                <input type="submit" value="{% trans 'Save' %}" class="default" />
                <input type="submit" value="{% trans 'Save and continue editing' %}" class="" name="_continue" />
            </div>
        </div>
    </form>
</div>
{% endblock %}

page_editor/templates/page_editor/createdir.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load admin_static i18n fb_tags fb_csrf fb_compat %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}
{% block coltype %}colM{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "page_editor/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <!-- POP-UP BREADCRUMBS -->
    {% if query.pop %}
        {% include "page_editor/include/breadcrumbs.html" %}
    {% endif %}
    <form action="{% query_string '' 'p' %}" method="post">{% fb_csrf_token %}
        <div>
            {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
            <fieldset class="module aligned wide">
                <div class="form-row field-{{ form.name.name }}{% if form.name.errors %} errors{% endif %}">
                    {% if form.name.errors %}{{ form.name.errors }}{% endif %}
                    <div>
                        <label class="required" for="id_dir_name">{{ form.name.label }}</label>
                        {{ form.name }}
                        <p class="help">
                            {{ form.name.help_text|safe }}
                            {% if settings_var.NORMALIZE_FILENAME or settings_var.CONVERT_FILENAME %}
                                <br />
                                {% if settings_var.NORMALIZE_FILENAME %}
                                    {% trans "The Name will be normalized by converting or stripping all non-standard characters." %} <br />
                                {% endif %}
                                {% if settings_var.CONVERT_FILENAME %}
                                    {% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                </div>
            </fieldset>
            <div class="submit-row">
                <input type="submit" value="{% trans 'Submit' %}" class="default" />
            </div>
        </div>
    </form>
</div>
{% endblock %}

page_editor/templates/page_editor/custom_field.html
{% load i18n fb_versions %}
<input id="{{ final_attrs.id }}" type="text" class="vFileBrowseField{% if final_attrs.class %} {{ final_attrs.class }}{% endif %}" name="{{ final_attrs.name }}" value="{{ value.path }}" {% for k, v in final_attrs.data_attrs.items %}{{k}}="{{v}}" {% endfor %}/>
<a href="#" onclick="FileBrowser.show(this.parentNode.getElementsByTagName('input')[0].id, '{{ url }}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory|urlencode|urlencode }}{% endif %}{% if final_attrs.format %}&amp;filter={{ final_attrs.format }}{% endif %}');" class="fb_show">
    <img src="{{ final_attrs.search_icon }}" alt="{% trans "Change" %}" />
</a>
{% if value.filetype == "Image" and value.exists %}
{% version value.path final_attrs.ADMIN_THUMBNAIL as thumbnail_version %}
{% if thumbnail_version %}
<p class="preview" id="preview_{{ final_attrs.id }}">
    <a href="{{ value.url }}" target="_blank" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" src="{{ thumbnail_version.url }}" class="preview" />
    </a>
</p>
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% if value and not value.exists %}
<ul class="errorlist"><li>{% trans "File not found" %}</li></ul>
{% endif %}

page_editor/templates/page_editor/custom_upload_field.html
{% load i18n fb_versions %}
<div class="fb-uploadfield{% if value and not value.exists %} error{% endif %}">
<input id="{{ final_attrs.id }}" type="text" class="vTextField vFileBrowseUploadField" name="{{ final_attrs.name }}" value="{{ value.path }}" /><div id="{{ final_attrs.id }}-uploader" class="fb-uploader-container"></div><a href="javascript:FileBrowser.show('{{ final_attrs.id }}', '{{ url }}?pop=1{% if final_attrs.directory %}&amp;dir={{ final_attrs.directory|urlencode|urlencode }}{% endif %}{% if final_attrs.format %}&amp;type={{ final_attrs.format }}{% endif %}');" class="fb_show"></a>
{#<div class="progress-bar"><div class="content"></div></div>#}
{% if value and not value.exists %}
<ul class="errorlist"><li>{% trans "File not found" %}</li></ul>
{% endif %}
</div>
{% if value.filetype == "Image" %}
{% version value.path final_attrs.ADMIN_THUMBNAIL as thumbnail_version %}
{% if thumbnail_version %}
<p class="preview" id="preview_{{ final_attrs.id }}">
    <a href="{{ value.url }}" target="_blank" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" src="{{ thumbnail_version.url }}" class="preview" />
    </a>
</p>
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}
{% else %}
<p class="preview" id="preview_{{ final_attrs.id }}" style="display: none;">
    <a href="javascript://" target="_self" id="previewlink_{{ final_attrs.id }}">
        <img id="previewimage_{{ final_attrs.id }}" class="preview" src="" />
    </a>
</p>
{% endif %}

<script type="text/javascript">
    (function($){
        $(document).ready(function() {
            var uploader = new qq.FileUploader({
                element: $('#{{ final_attrs.id }}-uploader').get(0),
                action: '{% url "page_editor:fb_do_upload" %}',

                template: '<div class="fb-uploader">' +
                        '<div class="fb-upload-list"></div>' +
                        '<a href="javascript://" class="fb-upload-button" title="{% trans "Upload a file" %}">&nbsp;</a>' +
                        '<div class="fb-upload-drop-area"><span>Drop files here to upload</span></div>' +
                    '</div>',

                // template for one item in file list
                fileTemplate: '<div class="fb-upload-item">' +
                        '<span class="fb-upload-file"></span>' +
                        '<span class="fb-upload-spinner">&nbsp;</span>' +
                        '<span class="fb-upload-size"></span>' +
                        '<a class="fb-upload-cancel" href="#"></a>' +
                        '<span class="fb-upload-failed-text"></span>' +
                        '<div class="progress-bar"><div class="content"></div></div>' +
                    '</div>',

                classes: {
                    // used to get elements from templates
                    button: 'fb-upload-button',
                    drop: 'fb-upload-drop-area',
                    dropActive: 'fb-upload-drop-area-active',
                    list: 'fb-upload-list',

                    file: 'fb-upload-file',
                    spinner: 'fb-upload-spinner',
                    size: 'fb-upload-size',
                    cancel: 'fb-upload-cancel',

                    // added to list item when upload completes
                    // used in css to hide progress spinner
                    success: 'fb-upload-success',
                    fail: 'fb-upload-fail'
                },

                params: { 'csrf_token': '{{ csrf_token }}',
                          'csrf_name': 'csrfmiddlewaretoken',
                          'csrf_xname': 'X-CSRFToken',
                          'temporary': 'true',
                          'folder': '{{ final_attrs.temp_upload_dir }}', },

                minSizeLimit: 0,
                debug: false,

                getItem: function(id) {
                    var items = $(this.element).find('.fb-upload-file').get();
                    var item = items.pop();

                    while (typeof item != "undefined") {
                        if (item.qqFileId == id) {
                            return $(item);
                        }
                        item = items.pop();
                    }
                },
                onProgress: function(id, fileName, loaded, total){
                    var bar = $(this.element).find('.progress-bar .content');
                    var new_width = '' + (loaded/total * 100) + '%';
                    bar.css('width', new_width);
                },
                onComplete: function(id, fileName, resp){
                    if (resp.success) {
                        $(this.element).find('.progress-bar').fadeOut();
                        $('#{{ final_attrs.id }}').val(resp.temp_filename);
                    }
                },
                showMessage: function(message){ alert(message); }
            });
        });
    })(django.jQuery);
</script>

page_editor/templates/page_editor/detail.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load admin_static i18n fb_tags fb_versions fb_compat %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
       <style>
    .html-editor{
        width: 100%;
        height: 350px;
        margin-top: 30px;
    }
    </style>
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static_jquery %}"></script>
    <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
    <script type="text/javascript">
    (function($) {
        $(document).ready(function() {
            // remove edit module if no actions are given
            if ($("select#id_custom_action").find("option").length <= 1) {
                $("fieldset#fieldset_edit").hide();
            }
        });
    })(django.jQuery);
    </script>
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}
{% block coltype %}colM{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "page_editor/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
    <!-- POP-UP BREADCRUMBS -->
    {% if query.pop %}
        {% include "page_editor/include/breadcrumbs.html" %}
    {% endif %}
    <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post">{% csrf_token %}
        <div>
            {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
            <fieldset class="module aligned">
                <div class="form-row field-{{ form.name.name }}{% if form.name.errors %} errors{% endif %}">
                    {% if form.name.errors %}{{ form.name.errors }}{% endif %}
                    <div>
                        <label class="required" for="id_name">{{ form.name.label }}</label>
                        {{ form.name }}
                        {% if form.name.help_text %}<p class="help">{{ form.name.help_text|safe }}</p>{% endif %}
                    </div>
                    <div>
                        {% if fileobject.filetype == "Image" %}
                            <img src="{{ fileobject.url }}" width="50%" style="margin-top: 30px">
                        {% elif fileobject.filetype == 'JS Script' or fileobject.filetype == 'CSS' or fileobject.filetype == 'Template' %}

                             {{ form.text }}
                        {% endif %}

                    </div>
                </div>
            </fieldset>
            <fieldset class="module aligned" id="fieldset_edit">
                <h2>{% trans "Edit" %}</h2>
                <div class="form-row {% if form.custom_action.errors %}errors{% endif %}">
                    {% if form.custom_action.errors %}{{ form.custom_action.errors }}{% endif %}
                    <div>
                        <label class="required" for="id_custom_action">{{ form.custom_action.label }}</label>
                        {{ form.custom_action }}
                        {% if form.custom_action.help_text %}<p class="help">{{ form.custom_action.help_text|safe }}</p>{% endif %}
                    </div>
                </div>
            </fieldset>
            {% if fileobject.filetype == "Folder" %}
            <fieldset class="module aligned">
                <h2>{% trans "Folder Information" %}</h2>
                <div class="form-row">
                    <div>
                        <label>{% trans "Date" %}</label>
                        <p>
                            {{ fileobject.datetime|date:"N j, Y" }}
                        </p>
                    </div>
                </div>
            </fieldset>
            {% endif %}
            {% if fileobject.filetype != "Folder" %}
            <fieldset class="module aligned">
                <h2>{% trans "File Information" %}</h2>
                <div class="form-row">
                    <div>
                        <label>{% trans "URL" %}</label>
                        <p>
                            <a href="{{ fileobject.url }}">{{ fileobject.url }}</a>
                        </p>
                    </div>
                </div>
                <div class="form-row">
                    <div>
                        <label>{% trans "Filesize" %}</label>
                        <p>
                            {{ fileobject.filesize|filesizeformat }}
                        </p>
                    </div>
                </div>
                <div class="form-row">
                    <div>
                        <label>{% trans "Date" %}</label>
                        <p>
                            {{ fileobject.datetime|date:"N j, Y" }}
                        </p>
                    </div>
                </div>
                {% if fileobject.filetype == "Image" %}
                    <div class="form-row">
                        <div>
                            <label>{% trans "Size" %}</label>
                            <p>
                                {{ fileobject.width }} x {{ fileobject.height }} px
                            </p>
                        </div>
                    </div>
                {% endif %}
            </fieldset>
            {% endif %}

            <div class="submit-row">
                <p class="deletelink-box">
                    <a href="{% url 'page_editor:fb_delete_confirm' %}{% query_string %}" class="deletelink">{% trans "Delete" %}</a>
                </p>
                <input type="submit" value="{% trans 'Save' %}" class="default" />
                <input type="submit" value="{% trans 'Save and continue editing' %}" class="" name="_continue" />
            </div>
        </div>
    </form>
</div>
{% endblock %}